# Generated by Django 3.1.4 on 2020-12-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название аппартамента')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('rooms', models.CharField(max_length=255, verbose_name='Комнат')),
                ('place', models.CharField(max_length=255, verbose_name='Квадратных метров')),
                ('roomType', models.CharField(max_length=255, verbose_name='Тип (Дом или Квартира)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефонма')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='appartments')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='appartments')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='appartments')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='appartments')),
            ],
        ),
    ]
