# Generated by Django 3.1.4 on 2020-12-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartments', '0002_appartments_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartments',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='appartments',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='appartments',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='appartments',
            name='image4',
        ),
    ]
